### PR TITLE
Updated Italian translation

### PR DESCRIPTION
**Pull request by henrythebuilder**
Updated localized text for Italian (it)

### CODE REVIEW

**Comment by senshu** [comment]
I have also uploaded your modifications to https://translations.launchpad.net/sozi
A new build of Sozi 18.03 will be available at https://drive.google.com/drive/folders/0ByRUreHgekjMWG9teGM2dE8wck0

**Comment by henrythebuilder** [comment]
Many thanks!
I have some trouble compiling Sozi from source so your new build is welcome :+1:

**Comment by senshu** [comment]
> I have some trouble compiling Sozi from source

Can you open a new issue and give me more information about your problems?

**Comment by henrythebuilder** [comment]
Ok, probably it is a my local problem, however I will proceed to create a new issue, thank for the support.

**Pull request merged**
